[env]
MISE_CONFIG_ROOT = '{{config_root}}'

[tools]
node = "latest"
deno = "latest"
python = "latest"
uv = "latest"
yarn = "latest"
pnpm = "latest"

[settings]
quiet = true
experimental = true

[tasks.aws]
run = ["aws"]

[tasks.claude]
run = ["claude --debug"]
